language: objective-c
osx_image: xcode7.1
script:
  - xctool -project StomtiOS.xcodeproj -scheme StomtiOS -sdk iphonesimulator9.1 -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=NO build test
